config/routes.rb
Rails.application.routes.draw do
  apipie
  # devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #

  scope module: 'admin' do
    devise_for :admins, controllers: {
        sessions: 'admin/admins/sessions',
        registrations: 'admin/admins/registrations',
        passwords: 'admin/admins/passwords'
    }
  end

  namespace :admin do
    resources :coins
    resources :shops
    resources :admins, except: [:edit, :update]
    resources :users, only: [:index, :destroy]
    resources :boards, only: [:index, :destroy] do
      resources :responses, only: [:index, :show, :destroy]
    end

  end

  namespace :public do
    root to: 'coins#index'

    resources :coins, only: :index
    resources :shops, only: [:index, :show]
    resources :user_responses, only: [:index, :destroy]
    resources :boards, only: [:index, :new, :create] do
      resources :responses, only: [:index, :new, :create]
      collection do
        resources :responses, only: [:destroy]
      end
    end
  end

  scope module: :user do
    devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: 'public/users/passwords'
    }
  end


  # API
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          registrations: 'api/v1/auth/registrations'
      }

      resources :coins, only: :index
      resources :shops, only: [:index, :show]
      resources :boards, only: [:index, :create] do
        resources :responses, only: [:index, :create, :destroy]
      end
      resources :user_responses, only: :index
    end
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  # アソシエーション
  has_many :coin_shops, dependent: :destroy
  has_many :coins, through: :coin_shops

  validates :name, presence: true
  validates :address, presence: true
  validates :company, presence: true
  # validates :coin_shops, presence: true
  #

  # スコープ
  scope :search_name, -> (q) { where("#{self.table_name}.name like ?", "%#{q}%") }
  scope :search_address, -> (q) { where("#{self.table_name}.address like ?", "%#{q}%") }
  scope :search_company, -> (q) { where("#{self.table_name}.company like ?", "%#{q}%") }



end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < Admin::ApplicationController

  before_action :get_shop, only: [:show, :edit, :update, :destroy]

  def index
    @params = params
    @coin_ids = params[:coin_ids].present? ? params[:coin_ids] : []
    get_slhops_service = GetShopsService.new(@params, @coin_ids)
    @shops             = get_slhops_service.call
    @coins             = Coin.all
  end

  def new
    @shop = Shop.new()
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      flash[:success] = "取引所を登録しました"
      redirect_to admin_shops_path
    else
      flash.now[:danger] = "不正な入力値です"
      render :new
    end
  end

  def show
  end

  def eidt
  end

  def update
    CoinShop.destroy(@shop.coin_shops.ids)
    if @shop.update(shop_params)
      flash[:success] = "取引所を更新しました"
      redirect_to admin_shop_path
    else
      flash.now[:danger] = "不正な入力値です"
      render :edit
    end
  end

  def destroy
    begin
      @shop.destroy!
    rescue => e
      flash[:danger] = "取引所の削除に失敗しました"
      logger.error "[error] #{e.message}"
      redirect_back(fallback_location: admin_shops_path) and return
    end
    flash[:success] = "取引所を削除しました"
    redirect_to admin_shops_path
  end


  private
  def shop_params
    params.require(:shop).permit(:name, :address, :company, coin_ids: [])
  end

  def get_shop
    @shop = Shop.find(params[:id])
  end
end

app/controllers/api/v1/shops_controller.rb
class Api::V1::ShopsController < Api::V1::ApplicationController

  api :GET, 'v1/shops', '取引所一覧を返します'
  description '取引所一覧を返します'
  formats ['json']
  param :q, String, :desc => "取引所名・住所・会社名"
  param :coin_ids, Array, :desc => "[1, 2, 3]"
  example <<-EDOC
  $ curl http://localhost:3000/shops?q=コインチェック&coins_ids=[1, 2]
    {
    "shops": [
      {
        "name": "コインチェック",
        "address": "東京都渋谷区神泉2-18-9",
        "company": "株式会社コインチェック",
        "created_at": "2019-01-16T20:50:05+09:00",
        "updated_at": "2019-01-16T20:50:05+09:00",
        "coins": [
          {
            "id": 1,
            "name": "Bitcoin",
            "symbol": "BTC",
            "rank": 1,
            "price_jpy": "398431.560002",
            "market_cap_jpy": "6966411274404",
            "created_at": "2019-01-16T20:50:05+09:00",
            "updated_at": "2019-01-16T20:50:05+09:00"
          },
          {
            "id": 2,
            "name": "XRP",
            "symbol": "XRP",
            "rank": 2,
            "price_jpy": "36.1899421435",
            "market_cap_jpy": "1485249885936",
            "created_at": "2019-01-16T20:50:05+09:00",
            "updated_at": "2019-01-16T20:50:05+09:00"
          },
          {
            "id": 3,
            "name": "Ethereum",
            "symbol": "ETH",
            "rank": 3,
            "price_jpy": "13529.1527337",
            "market_cap_jpy": "1412482493278",
            "created_at": "2019-01-16T20:50:05+09:00",
            "updated_at": "2019-01-16T20:50:05+09:00"
          }
        ]
      },
      {
        "name": "ビットフライヤー",
        "address": "東京都みn区神泉2-18-9",
        "company": "株式会社コインチェック",
        "created_at": "2019-01-16T20:50:05+09:00",
        "updated_at": "2019-01-16T20:50:05+09:00",
        "coins": [
          {
            "id": 1,
            "name": "Bitcoin",
            "symbol": "BTC",
            "rank": 1,
            "price_jpy": "398431.560002",
            "market_cap_jpy": "6966411274404",
            "created_at": "2019-01-16T20:50:05+09:00",
            "updated_at": "2019-01-16T20:50:05+09:00"
          },
          {
            "id": 2,
            "name": "XRP",
            "symbol": "XRP",
            "rank": 2,
            "price_jpy": "36.1899421435",
            "market_cap_jpy": "1485249885936",
            "created_at": "2019-01-16T20:50:05+09:00",
            "updated_at": "2019-01-16T20:50:05+09:00"
          },
          {
            "id": 3,
            "name": "Ethereum",
            "symbol": "ETH",
            "rank": 3,
            "price_jpy": "13529.1527337",
            "market_cap_jpy": "1412482493278",
            "created_at": "2019-01-16T20:50:05+09:00",
            "updated_at": "2019-01-16T20:50:05+09:00"
          }
        ]
      }
    ],
    "meta": {
      "total_pages": 1,
      "current_page": 1,
      "total_count": 2,
      "limit_value": 30,
      "links": {
          "self": "http://0.0.0.0/api/v1/shops?page%5Bnumber%5D=1&page%5Bsize%5D=2&q=%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF"
      }
    }
  EDOC

  def index
    coin_ids = params[:coin_ids].present? ?  params[:coin_ids]: nil
    # Todo パラメータのリファクタリング
    @shops         = GetShopsService.new(params, coin_ids).call
    set_query_string_to_hash
    render 'index', formats: 'json', handlers: 'jbuilder'
  end


  api :GET, '/v1/shops/:id', '取引所を返します'
  description '取引所を返します'
  formats ['json']
  param :id, :number, desc: 'shop id', required: true
  example <<-EDOC
  $ curl http://localhost/api/vi/shops/1
  {
    "name": "コインチェック",
    "address": "東京都渋谷区神泉2-18-9",
    "company": "株式会社コインチェック",
    "created_at": "2019-01-16T20:50:05+09:00",
    "updated_at": "2019-01-16T20:50:05+09:00",
    "coins": [
      {
        "id": 1,
        "name": "Bitcoin",
        "symbol": "BTC",
        "rank": 1,
        "price_jpy": "398431.560002",
        "market_cap_jpy": "6966411274404",
        "created_at": "2019-01-16T20:50:05+09:00",
        "updated_at": "2019-01-16T20:50:05+09:00"
      },
      {
        "id": 2,
        "name": "XRP",
        "symbol": "XRP",
        "rank": 2,
        "price_jpy": "36.1899421435",
        "market_cap_jpy": "1485249885936",
        "created_at": "2019-01-16T20:50:05+09:00",
        "updated_at": "2019-01-16T20:50:05+09:00"
      },
      {
        "id": 3,
        "name": "Ethereum",
        "symbol": "ETH",
        "rank": 3,
        "price_jpy": "13529.1527337",
        "market_cap_jpy": "1412482493278",
        "created_at": "2019-01-16T20:50:05+09:00",
        "updated_at": "2019-01-16T20:50:05+09:00"
      }
    ]
}

  EDOC
  def show
    begin
      @shop = Shop.find(params[:id])
    rescue
      render_error 500, "idに紐づく取引所を取得できませんでした" and return
    end
    render 'show', formats: 'json', handlers: 'jbuilder'
  end
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
  def get_coin_check_box_tag coind_id
    @coin_ids.include?(coind_id.to_s) ? check_box_tag("coin_ids[]", coind_id, true, id: "coin_#{coind_id}") : check_box_tag("coin_ids[]", coind_id, false, id: "coin_#{coind_id}")
  end
end

app/helpers/api/v1/shops_helper.rb
module Api::V1::ShopsHelper
end

app/views/admin/shops/_form.html.erb
<%= form_for [:admin, @shop], :html => { :class => "form-horizontal shop" } do |f| %>

  <% if @shop.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :company, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "取り扱いコイン", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_check_boxes(:coin_ids, Coin.all, :id, :name, include_hidden: false) do |b| %>
        <%= b.label { b.check_box + b.text } %><br>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/admin/shops/edit.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/shops/index.html.erb
<div class="page-header">
  <h1>取引所</h1>
  <%= form_tag admin_shops_path, method: :get do %>
    <div class="form-group">
      <div class="col-lg-10">
        <%= text_field_tag :q, @params[:q], class: 'form-control', placeholder: "取引所名・住所・会社名" %>
      </div>
    </div>
    <br><br><br>

    <div>
      <% @coins.each.with_index(1) do |coin, i| %>
        <%= get_coin_check_box_tag(coin, @coin_ids) %>
        <%= label_tag :coin_name, coin.name %>
        <% if i % 6 == 0 %>
          <br>
        <% end %>
      <% end %>
    </div>
    <br><br>
    <div><%= submit_tag "検索", class: 'btn btn-primary' %></div>
  <% end %>
  <br><br><br>
  <div>
    <%= link_to "新規作成", new_admin_shop_path %>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>取引所名</th>
      <th>住所</th>
      <th>会社名</th>
      <th>取り扱いコイン</th>
      <th>詳細</th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.id %></td>
        <td><%= shop.name %></td>
        <td><%= shop.address %></td>
        <td><%= shop.company %></td>
        <td>
          <% shop.coins.reload.each do |coin| %>
            <%= coin.name %><br>
          <% end %>
        </td>
        <td><%= link_to "詳細", admin_shop_path(shop), {id: "shop_#{shop.id}", class: "btn btn-info"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= paginate @shops, class: "page-link" %>
</div>

app/views/admin/shops/new.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1>取引所作成</h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/shops/show.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1>取引所詳細</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>取引所名:</strong></dt>
  <dd><%= @shop.name %></dd>
  <dt><strong>住所:</strong></dt>
  <dd><%= @shop.address %></dd>
  <dt><strong>会社名:</strong></dt>
  <dd><%= @shop.company %></dd>
  <dt><strong>取り扱いコイン:</strong></dt>
  <dd>
    <% @shop.coins.each do |coin| %>
      <%= coin.name %><br>
    <% end %>
  </dd>
</dl>
<div>
  <%= link_to "編集", edit_admin_shop_path(@shop), class: "btn btn-success" %>
  <%= link_to "削除", admin_shop_path(@shop), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger" %>
</div>