config/routes.rb
Rails.application.routes.draw do
  apipie
  # devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #

  scope module: 'admin' do
    devise_for :admins, controllers: {
        sessions: 'admin/admins/sessions',
        registrations: 'admin/admins/registrations',
        passwords: 'admin/admins/passwords'
    }
  end

  namespace :admin do
    resources :coins
    resources :shops
    resources :admins, except: [:edit, :update]
    resources :users, only: [:index, :destroy]
    resources :boards, only: [:index, :destroy] do
      resources :responses, only: [:index, :show, :destroy]
    end

  end

  namespace :public do
    root to: 'coins#index'

    resources :coins, only: :index
    resources :shops, only: [:index, :show]
    resources :user_responses, only: [:index, :destroy]
    resources :boards, only: [:index, :new, :create] do
      resources :responses, only: [:index, :new, :create]
      collection do
        resources :responses, only: [:destroy]
      end
    end
  end

  scope module: :user do
    devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: 'public/users/passwords'
    }
  end


  # API
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          registrations: 'api/v1/auth/registrations'
      }

      resources :coins, only: :index
      resources :shops, only: [:index, :show]
      resources :boards, only: [:index, :create] do
        resources :responses, only: [:index, :create, :destroy]
      end
      resources :user_responses, only: :index
    end
  end
end

app/views/admin/admins/_form.html.erb
<%= form_for [:admin, @admin], :html => { :class => "form-horizontal admin" } do |f| %>

  <% if @admin.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @admin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password_confirmation, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/admin/admins/index.html.erb
<div class="page-header">
  <h1>管理者管理</h1>
  <%= form_tag admin_admins_path, method: :get do %>
    <div class="form-group">
      <div class="col-lg-10">
        <%= text_field_tag :q, @q, class: 'form-control', placeholder: "苗字・名前・苗字 名前・メールアドレス" %>
      </div>
    </div>
    <%= submit_tag "検索", class: 'btn btn-primary' %>
  <% end %>
  <br><br><br>
  <div>
    <%= link_to "新規作成", new_admin_admin_path %>
  </div>

</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>苗字</th>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th>詳細</th>

    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.id %></td>
        <td><%= admin.last_name %></td>
        <td><%= admin.first_name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></td>
        <td><%= admin.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %></td>
        <td><%= link_to "詳細", admin_admin_path(admin), class: "btn btn-info", id: "admin_#{admin.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <div>
    <%= paginate @admins, class: "page-link" %>
  </div>
</div>

app/views/admin/admins/new.html.erb
<div class="page-header">
  <h1>管理者作成</h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/admins/show.html.erb
<div class="page-header">
  <h1>管理者詳細</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>苗字:</strong></dt>
  <dd><%= @admin.last_name %></dd>
  <dt><strong>名前:</strong></dt>
  <dd><%= @admin.first_name %></dd>
  <dt><strong>メールアドレス:</strong></dt>
  <dd><%= @admin.email %></dd>
  <dt><strong>作成日時:</strong></dt>
  <dd><%= @admin.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></dd>
  <dt><strong>更新日時:</strong></dt>
  <dd><%= @admin.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></dd>
</dl>
<div>
  <%= link_to "削除", admin_admin_path(@admin), method: :delete, class: "btn btn-danger", data: {confirm: "本当に削除しますか？"} %>
</div>